name = "office-guestbook"
account_id = "${CLOUDFLARE_ACCOUNT_ID}"

main = "./.cloudflare/worker.js"
site.bucket = "./.cloudflare/public"

build.command = "npm run build"

compatibility_date = "2021-11-12"
workers_dev = true