name: buildAndDeployWorker
on:
  push:
    branches:
      - production
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    name: Deploy
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - name: Publish
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
